#+title: 数字电路
#+subtitle: verilog
#+author: Joe
#+latex_class: org-latex-pdf 
#+toc: tables 
#+toc: listings 
#+latex: \clearpage\pagenumbering{arabic} 
#+latex: \AddToShipoutPicture{\BackgroundPicture} 
#+options: h:4 ^:{} 
#+startup: overview
* 基本语法
** 寄存器reg
包含多个类型，寄存器可能被综合为一个触发器（数字建构）、一个锁存器（模
拟建构）或一根导连线，甚至可能在优化时被去掉。
- integer：整数默认位宽为缩主机的字长，最小为32位，且为有符号类型。
- real
- time
** 门级建模
** 数据流级建模
- 通过EDA设计工具，自动将电路的数据流设计直接转换为门级结构，被称为逻
  辑综合。
- RTL级：通常指数据流级和行为级的结合。


数据流级包含的语法
- 连续赋值语句：assign
- 表达式语句：如+-*/等
  + 算术操作符
  + 逻辑操作符
  + 关系操作符
  + 等价操作符
  + 按位操作符
  + 缩减操作符
  + 移位操作符
  + 拼接操作符
  + 复制操作符
  + 条件操作符，
** 行为级建模
行为级包含的语法
- always/initial：以下的所有行为语句都要在这2个结构化语句中。每个
  always和initial语句代表1个独立的执行过程，每个执行过程从仿真时间0开
  始执行，且不能嵌套使用。
- if/else
- case/casex/casez
- while/for/repeat/forever
- 过程赋值：过程赋值语句只在执行到的时候才会起作用（注意和数据流的连续
  赋值assign的区别，assign总是活动状态，任意一个操作数变化都会导致表达
  式重新计算）。
  + 阻塞赋值语句：使用“=”作为赋值符。
  + 非阻塞赋值语句：使用“<=”作为赋值符号。


* 任务函数
- $finish：表示为断电；
- $stop：中断；
* 基本门电路
- 与门
- 或门
- 非门
- 异或门
* 组合逻辑
组合逻辑是一种数字电路，其输出只与输入状态有关。


- 时间延迟：在实际的IC/FPGA逻辑电路中，组合逻辑是有时间延迟的，也就是
  说组合逻辑的输入变化到输出变化之前是有时间的。
- 逻辑级数：指组合逻辑的深度，深度越大组合逻辑越复杂，延迟越大。


信号在IC/FPGA器件内部通过连线和逻辑单元时，都有一定的延时，延时的大小
与连线的长短和逻辑单元的数目有关，还受器件的制造工艺、工作电压、温度等
的影响。信号的高低电平转换也需要一定的过渡时间。由于存在这2方便因素，
多路信号的电平值发生变化时，在信号变化的瞬间，组合逻辑的输出有先后顺序，
并不是同时变化，往往会出现一些不正确的尖峰信号，这些尖峰信号称为毛刺。


信号在器件中传输时，所需要的时间是不能精确估计的，当多路信号同时发生跳
变的瞬间，就产生了“竞争冒险”，这时常会出现一些不正确的尖峰信号，即毛刺。
** 去毛刺
*** 组合逻辑输出加寄存器
加寄存器去毛刺的原理就是用一个寄存器去读带毛刺的信号，利用寄存器对输入
信号的毛刺不敏感的特点（寄存器一般只在时钟跳变沿对输入信号敏感），去除
信号中的毛刺，但是如果信号毛刺发生在时钟信号的跳变沿，寄存器的输出端仍
含有毛刺。



另外，寄存器还会给系统带来一定的延时，特别是在系统级数较多的情况下，延
时也将变大。
*** 信号同步法
同步电路设计可以大大减少毛刺。由于大多数毛刺都比较短（几纳秒），只要毛
刺不出现在时钟跳变沿，毛刺信号就不会对系统造成危害。通常，在整个系统中
使用同一个时钟就可以实现系统同步。但是时钟信号在FPGA器件中传递时是有延
迟的，无法预知时钟跳变沿的精确位置。即，无法保证时钟跳变沿读取的数据是
一个稳定的数据。因此，做到真正的同步就是去除毛刺信号的关键，保证在时钟
跳变沿读取的数据是稳定的数据而不是毛刺数据。信号同步的方法有2种。
- 信号延时同步法：就是在信号传递的过程中加一个延时环节，使得各个信号同
  时到达逻辑门。
- 状态机控制法：由状态机在特定的时刻分别发出控制特定模块的时钟信号或使
  能信号，状态机的循环控制就可以使得整个系统协调运作，同时减少毛刺信号。
  那只要在状态机触发时间上加以处理，就可以避免竞争冒险，从而抑制毛刺。
* 时序逻辑
时序逻辑是一种数字电路，其输出不只与输入状态有关还与之前的输出有关，本
质上，时序逻辑电路由组合逻辑和存储逻辑构成，组合逻辑完成输入到输出的逻
辑处理，处理结果同时会进入存储逻辑里面存储起来，等到下一刻在和输入的信
号作逻辑处理，存储电路一般组成有。
- 锁存器（Latch）：是电平触发的存储单元，数据存储的动作取决于输入时钟
  信号的电平值，即当锁存器处于使能状态时，输出才会随着数据输入发生变化。
  锁存器的缺点是不能过滤毛刺。
  + RS锁存器
  + 门控RS锁存器
  + D锁存器
- 触发器（flip-flop）：是边沿敏感的存储单元，数据存储的动作由信号的边
  沿进行同步。
  + RS触发器
  + JK触发器
  + D触发器
  + T触发器
  + T'触发器
- 寄存器（register）：能够用来存储一组二进制代码的同步时序逻辑电路称为
  寄存器。


  
触发器和寄存器的区别：由于触发器内有记忆功能，因此利用触发器可以方便的
构成寄存器。由于一个触发器能存储一位二进制码，所以把n个触发器的时钟端
连接起来就构成了一个存储n位二进制的寄存器。



寄存器和锁存器的功能是相同的，区别在于寄存器是同步时钟控制，锁存器是电
位信号控制。
** 锁存器
在组合逻辑中，if或者case语句不完整的描述，比如if缺少else分支，case缺少
default分支，导致代码在综合过程中出现latch，所以实际使用中if必须带else
分支，case必须带default分支。但是，只有不带时钟的always语句的if或case
语句不完整才会产生latch，带时钟的语句if或case语句不完整描述不会产生
latch。
** 触发器
触发器对脉冲边沿敏感的存储单元电路，它只在触发脉冲上升沿或下降沿瞬间改
变状态。
** 寄存器
寄存器是构成时序逻辑最重要的单元，可以说没有寄存器就没有时序逻辑。寄存
器是由多个触发器组成。
* 基本电路
** 计数器
** 边沿检测电路
** 格雷码转换电路
** 复位电路
结合同步和异步复位的优缺点，比较好的复位方式是：异步复位、同步释放，且
复位信号为低电平有效。
- 复位信号到来的有效性与clk无关，且复位信号的撤除也与clk无关，但是复位
  信号的撤除是在下一个clk来到后才起作用。
- 异步复位同步撤离的目的为了防止复位信号撤除时，可能产生亚稳态。

#+begin_src verilog
  always @(posedge clk or negedge rst_async_n) begin
     if (!rst_async_n) begin
        rst_s1 <= 1'b0;
        rst_s2 <= 1'b0;
     end
     else begin
        rst_s1 <= 1'b1;
        rst_s2 <= rst_s1;
     end
  end

     assign rst_sync_n = rst_s2;

  always @(posedge clk or negedge rst_sync_n) begin
     if (rst_sync_n == 1'b0)
       y <= 1'b0;
     else
       y <= b;
  end   
#+end_src   
 
*** 同步复位
同步复位指的是当时钟上升沿检测到复位信号，执行复位操作，有效的时钟沿是
前提。
#+begin_src verilog
  always @(posedge clk) begin
     if (rst_n == 1'b0)
       y <= 1'b0;
     else
       y <= b;
  end
#+end_src
- 优点
  + 有利于仿真器的仿真；
  + 可以使所设计的系统成为100%的同步时序电路，有利于时序分析，可综合出
    较高的Fmax；
  + 由于只在时钟有效电平到来时才有效，所以可以滤除高于时钟频率的复位毛
    刺；
- 缺点
  + 复位信号的有效时长必须大于时钟周期，才能真正被系统识别并完成复位任
    务，还要考虑时钟偏移、组合逻辑路径延时、复位延时等因素；
  + 由于大多数的逻辑器件的目标库内的DFF都只有异步复位端口，所以若采用
    同步复位，综合器就会在寄存器的数据输入端口插入组合逻辑，就会额外增
    加FPGA内部逻辑资源，还会增加相应的组合逻辑门延时；
*** 异步复位
异步复位指无论时钟沿是否到来，只要复位信号有效，就对系统进行复位，当时
钟上升沿检测到复位信号，执行复位操作。
#+begin_src verilog
  always @(posedge clk or negedge rst_n) begin
     if (rst_n == 1'b0)
       y <= 1'b0;
     else
       y <= b;
  end
#+end_src
- 优点
  + 大多数目标器件库的DFF都有异步复位端口，那么该触发器的复位端口就不
    需要额外的组合逻辑，省资源；
  + 设计相对简单；
  + 异步复位信号产生和响应都很方便（电路任何情况下都能复位而不管是否有
    时钟出现）；
- 缺点
  + 最大问题是它属于异步逻辑，问题出现在复位释放时，若复位释放接近时钟
    有效沿，则触发器的输出可能进入亚稳态（此时clk检测到的rst_n的状态就
    会是亚稳态，即是0是1不确定），从而导致复位失败。
  + 可能因为噪声或毛刺造成虚假复位信号（系统正常工作时突然复位）
  + 静态定时分析比较困难，静态时许分析一般都是针对同步设计的，都是基于
    时钟周期来分析时许的
  + 对于DFT设计，若复位信号不是直接来自于I/O引脚，在DFT扫描和测试时，
    复位信号必须被禁止，因此需要额外的同步电路。
* RAM
- 静态RAM(SRAM)
  + 单端口RAM(Single Port RAM)： SP RAM， 只有1个读写口，同时刻只能发
    起读或写；
  + 双端口RAM(Two Port RAM)：TP RAM，也叫伪双口，一个口只能读，一个口
    只能写；
  + 真双端口RAM(Dual Port RAM)：DP RAM，每个端口都可以读写；


 |--------+---------+-------|
 | 类型    | 数据读写 | 地址口 |
 |        |   口数量 |   数量 |
 |--------+---------+-------|
 |--------+---------+-------|
 | SP RAM |       1 |     1 |
 | TP RAM |       1 |     2 |
 | DP RAM |       2 |     2 |
 |--------+---------+-------|

- 动态RAM(SDRAM)
  + SDRAM
  + DDR SDRAM
  + DDR2 SDRAM
  + DDR3 SDRAM
  + DDR4 SDRAM
 
