#+title: 分析数据结构的内存布局
# #+subtitle: 
#+author: Joe
#+latex_class: org-latex-pdf 
#+toc: tables 
#+toc: listings 
#+latex: \clearpage\pagenumbering{arabic} 
#+latex: \AddToShipoutPicture{\BackgroundPicture} 
#+options: h:4 ^:{} 
#+startup: overview

* 背景
数据结构涵盖了数据成员的类型和大小以及各个成员的不同对齐要求.为了确保
每个数据成员满足内存对齐要求,编译器需要插入一些额外的空间(洞)到里面.作
为开发者,我们也想因为以下原因对数据结构一探究竟.
- 基于目标架构的对齐要求, 编译器自动添加孔洞使得数据成员对齐CPU的word
  大小.这会增加对象的总大小,因此需要意识到这个开销.
- 开发者可能会显示的添加孔洞来满足特定的对齐要求或内存布局,如,许多CPU
  架构再fetch数据时以cache-size块的大小进行,因此对齐的数据结构可以减小
  cache line交叉访问进而改进cache利用率.
- 如果没有正确的添加孔洞,共享在相同cache line的独立变量会导致无法共享.
  这会导致非必要的cache一致性并且导致较大的性能损失.


当脑中带着这些考虑进行数据结构设计时, 一个重要的东西就是理解这些结构的
内存布局.如果你正在处理自己的代码库, 可能对这些选项有一个较好的理解,
但是,如果遇到的是一个新代码或复杂数据结构,需要手动推测的情况,那就不是
一个轻松的事情了.如何系统性的挖掘和理解这些数据结构,正是pahole的价值所
在.
* Pahole的使用
pahole(Poke-a-hole)工具是作为dwarves套件工具一部分进行开发的. 当带着调
试信息(比如-g编译选项), 编译器会包含DWARF信息到目标二进制中.这些信息包
含类型,变量细节以及他们的内存位置. pahole读取这些DWARF信息并以一个直观
且易理解的方式展示. 这可以帮助开发者理解内存布局,对齐,数据孔洞,进而减
小这些由编译器插入的数据孔洞.

** 安装
在Ubuntu下,可以用标准的系统包安装dwarves
#+begin_src shell
  sudo apt-get update
  sudo apt-get install dwarves -y
#+end_src


从源码安装也不难.
#+begin_src shell
  # install dependencies
  apt-get install libdw-dev libdwarf-dev libelf-dev zlib1g-dev -y
  # get source repo and following typical cmake install
  git clone https://git.kernel.org/pub/scm/devel/pahole/pahole.git
  cd pahole/
  git submodule update --init --recursive
  mkdir build && cd build
  cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/install/pahole ..
  make -j && make install
  export PATH=$HOME/install/pahole/bin:$PATH
#+end_src

** 用法
这样pahole命令就能使用了,以下是一些命令行选项
#+begin_src shell
  $ pahole --help
  Usage: pahole [OPTION...] FILE
 
    -B, --bit_holes=NR_HOLES   Show only structs at least NR_HOLES bit holes
    -c, --cacheline_size=SIZE  set cacheline size to SIZE
    -C, --class_name=CLASS_NAME   Show just this class
    -E, --expand_types         expand class members
        --flat_arrays          Flat arrays
        --hex                  Print offsets and sizes in hexadecimal
    -H, --holes=NR_HOLES       show only structs with at least NR_HOLES holes
    -i, --contains=CLASS_NAME  Show classes that contains CLASS_NAME
    -I, --show_decl_info       Show the file and line number where the tags were
                               defined
        --lang=LANGUAGES       Only consider compilation units written in these
                               languages
        --lang_exclude=LANGUAGES   Don't consider compilation units written in
                               these languages
    -M, --show_only_data_members   show only the members that use space in the
                               class layout
    -y, --prefix_filter=PREFIX include PREFIXed classes
    -r, --rel_offset           show relative offsets of members in inner structs
    -R, --reorganize           reorg struct trying to kill holes
    -s, --sizes                show size of classes
    -S, --show_reorg_steps     show the struct layout at each reorganization step
    -z, --hole_size_ge=HOLE_SIZE   show only structs with at least one hole
    -?, --help                 Give this help list
#+end_src

** 例程
有如下数据结构
#+begin_src c
  // Structure representing an ion channel.
  struct Channel {
      char name[4];               // Name of the ion channel.
      double conductance;         // Conductance of the ion channel.
      int id;                     // Unique ID of the ion channel.
      double rpotential;          // Reversal potential of the ion channel.
      float current;              // Current associated with the ion channel.
      double prop[4];             // Additional properties array.
  };
  // Structure representing a compartment of a neuron.
  struct Compartment {
      Channel sodium_channel;     // Sodium ion channel characteristics.
      Channel potassium_channel;  // Potassium ion channel characteristics.
      int location;               // Location or segment of the neuron compartment.
  };
  // Structure representing a neuron.
  struct Neuron {
      int gid;                    // Unique ID for a neuron cell.
      Compartment compartments[3];// Array of neuron compartments.
  };
  // Allocate 5 objects to represent neuron cells.
  Neuron cells[5];
#+end_src

将代码保存到test.cpp中,并进行编译,产生test.o目标文件.
#+begin_src shell
  g++ test.cpp -g -c
#+end_src


有一些特定的问题可以有效展示pahole工具的好处.
*** 内存中这些结构体怎么安排,孔洞的位置和大小
首要且明显的是搞懂数据结构的内存布局.这可以很容易办到, 通过pahole命令
带上目标文件. pahole会添加c风格的注释来解释内存布局.下面每个成员都有2
个数字以c注释风格和以字节为单位指示数据成员的偏移和大小. 如果编译器引
入了孔洞, pahole会注解他们的大小. 最后, 会提供一个孔洞和大小的总结.
#+begin_src c
  $ pahole --class_name=Channel test.o
  struct Channel {
      char                       name[4];              /*     0     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     conductance;          /*     8     8 */
      int                        id;                   /*    16     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     rpotential;           /*    24     8 */
      float                      current;              /*    32     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     prop[4];              /*    40    32 */
      /* size: 72, cachelines: 2, members: 6 */
      /* sum members: 60, holes: 3, sum holes: 12 */
      /* last cacheline: 8 bytes */
  };
#+end_src

在上面的例子中,使用了--class_name命令行选项来仅仅分析Channel类型,输出
报告也不难理解.
- name成员起始于偏移0 并且4字节.
- conductance起始于偏移8并且8字节大小, 在它之前有一个4字节的孔洞,因为
  对double类型有8字节对齐要求.
- id起始于偏移16且4字节大小.
- rpotential起始于24并8字节大小,在此之前也有一个4字节孔洞来满足double
  类型的内存对齐要求.
- current成员起始于偏移32占据4字节.
- prop之前有4字节孔洞,起始于40,32字节大小.


一旦所有的成员都列出后, 数据结构的总结也会提供.
- 这个结构的总的大小(包含孔洞)是72字节, 跨越2条cacheline(假定默认的
  cacheline大小是64字节).
- 所有成员大小合并为60字节,总共有3个孔洞,他们的大小为12字节.
- 这个数据类型只使用了第二条cacheline的8字节(这里用last cacheline表示).


作为一个对比例子, 可以看看当使用32bit目标架构进行编译时的输出. 当对
double变量对齐要求是4字节时, 可以看到数据结构的布局.
#+begin_src c
  $ g++ -g test.cpp  -c -m32
  $ pahole --class_name=Channel test.o
  struct Channel {
      char                       name[4];              /*     0     4 */
      double                     conductance;          /*     4     8 */
      int                        id;                   /*    12     4 */
      double                     rpotential;           /*    16     8 */
      float                      current;              /*    24     4 */
      double                     prop[4];              /*    28    32 */
      /* size: 60, cachelines: 1, members: 6 */
      /* last cacheline: 60 bytes */
  } __attribute__((__packed__));
#+end_src
*** 如何重新安排数据成员来优化内存布局
在上面的输出报告中, 观察到Channel类型扩展到了2条cacheline, 总共72字节,
尽管它的成员实际大小时60字节,如何指示pahole进行更紧凑的结构安排?
#+begin_src c
  $ pahole --show_reorg_steps --reorganize --class_name=Channel test.o
  /* Moving 'id' from after 'conductance' to after 'name' */
  struct Channel {
      char                       name[4];              /*     0     4 */
      int                        id;                   /*     4     4 */
      double                     conductance;          /*     8     8 */
      double                     rpotential;           /*    16     8 */
      float                      current;              /*    24     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     prop[4];              /*    32    32 */
      /* size: 64, cachelines: 1, members: 6 */
      /* sum members: 60, holes: 1, sum holes: 4 */
  }
  /* Final reorganized struct: */
  struct Channel {
      char                       name[4];              /*     0     4 */
      int                        id;                   /*     4     4 */
      double                     conductance;          /*     8     8 */
      double                     rpotential;           /*    16     8 */
      float                      current;              /*    24     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     prop[4];              /*    32    32 */
      /* size: 64, cachelines: 1, members: 6 */
      /* sum members: 60, holes: 1, sum holes: 4 */
  };   /* saved 8 bytes and 1 cacheline! */
#+end_src

通过这些注释,可以显而易见的了解pahole做了什么.通过将id成员从它原来的位
置调到name后面, 就避免了2个孔洞总共8字节. 结果, Channel现在可以很整洁
的适配到一条cacheline上.
*** 在cacheline大小为x字节情况下数据结构如何布局
现如今, 大多数广泛使用的Intel/AMD/ARM CPU都有64字节的cacheline, 使得这
个问题少了些趣味.但是, 带有不同cacheline大小的CPU一点儿不陌生(如,
Power9就有128字节的cacheline). pahole提供了--cacheline_size的命令行选
项来挖掘任意cacheline大小的内存布局.
#+begin_src c
  $ pahole --cacheline_size=128 test.o
  struct Channel {
      char                       name[4];              /*     0     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     conductance;          /*     8     8 */
      int                        id;                   /*    16     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     rpotential;           /*    24     8 */
      float                      current;              /*    32     4 */
      /* XXX 4 bytes hole, try to pack */
      double                     prop[4];              /*    40    32 */
      /* size: 72, cachelines: 1, members: 6 */
      /* sum members: 60, holes: 3, sum holes: 12 */
      /* last cacheline: 72 bytes */
  };
#+end_src
*** 理解嵌套数据结构和他们的内存布局组织形式
到此,我们为了简便都聚焦在一个单一类型Channel上.让我们看看Neuron类型,它
包含了Compartment和Channel类型. 使用--expand_types命令行选项来展示
Neuron内存布局的细节.
#+begin_src c
  $ pahole --expand_types --class_name=Neuron test.o
  struct Neuron {
      int                        gid;                                         /*     0     4 */
      /* XXX 4 bytes hole, try to pack */
      struct Compartment {
          struct Channel {
              char       name[4];                                              /*     8     4 */
              /* XXX 4 bytes hole, try to pack */
              double     conductance;                                          /*    16     8 */
              int        id;                                                   /*    24     4 */
              /* XXX 4 bytes hole, try to pack */
              double     rpotential;                                           /*    32     8 */
              float      current;                                              /*    40     4 */
              /* XXX 4 bytes hole, try to pack */
              double     prop[4];                                              /*    48    32 */
          } sodium_channel; /*     8    72 */
          /* --- cacheline 1 boundary (64 bytes) was 16 bytes ago --- */
          struct Channel {
              char       name[4];                                              /*    80     4 */
              /* XXX 4 bytes hole, try to pack */
              double     conductance;                                          /*    88     8 */
              int        id;                                                   /*    96     4 */
              /* XXX 4 bytes hole, try to pack */
              double     rpotential;                                           /*   104     8 */
              float      current;                                              /*   112     4 */
              /* XXX 4 bytes hole, try to pack */
              double     prop[4];                                              /*   120    32 */
          } potassium_channel; /*    80    72 */
          /* --- cacheline 2 boundary (128 bytes) was 24 bytes ago --- */
          int                location;                                         /*   152     4 */
      } compartments[3]; /*     8   456 */
      /* size: 464, cachelines: 8, members: 2 */
      /* sum members: 460, holes: 1, sum holes: 4 */
      /* last cacheline: 16 bytes */
  };
#+end_src



